version: '3'
services:

  spire-server:
    build: docker/spire-server
    hostname: spire-server
    tty: true
    privileged: true
    volumes:
      - ./docker/spire-server/conf:/opt/spire/conf/server

  flag-service:
    build: docker/flag-service
    hostname: flag-service
    tty: true
    privileged: true
    links:
      - spire-server
    ports:
      - 9890:8090

  user-service:
    build: docker/user-service
    hostname: user-service
    tty: true
    privileged: true
    links:
      - spire-server

  user-webapp:
    build: docker/user-webapp
    hostname: user-webapp
    tty: true
    privileged: true
    links:
      - spire-server
      - flag-service
      - user-service
    ports:
      - 9891:8080
